title: Cat Facts
author: David Tetreau
email: david_tetreau@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  This was a blog that was created to meet the requirements of the Github Pages course on Github Labs.
  However, it became much more! The world now has a blog about cat facts! Just what it needed!

# social links
twitter_username: david_tetreau # DO NOT include the @ character, or else the build will fail!
github_username:  dtetreau251 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
